### ISSUE TITLE
Failed to pull image "registry.gitlab.ceh.ac.uk/eip/catalogue/solr:2.81.2"

### ISSUE THREAD

**Issue by geoff-marine** [NERC-CEH/datalab-k8s-manifests#164]
Hi,

Trying to deploy onto microk8s.  

This is the status of the pods:

`kube-system      coredns-86f78bb79c-d5tmt                        1/1     Running                      0          147m

kube-system      calico-node-qk75p                               1/1     Running                      0          165m

kube-system      calico-kube-controllers-847c8c99d-5v6xw         1/1     Running                      0          165m

metallb-system   speaker-l7rh7                                   1/1     Running                      0          117m

metallb-system   controller-559b68bfd8-j2pt9                     1/1     Running                      0          117m

kube-system      hostpath-provisioner-5c65fbdb4f-mscbr           1/1     Running                      0          112m

ingress          nginx-ingress-microk8s-controller-2qd4m         1/1     Running                      0          48m

default          catalogue-6d44b8d679-cc4qp                      0/1     Pending                      0          45m

default          mapserver-86bd9f6ff4-xzthg                      0/1     Pending                      0          45m

test             mongodb-deployment-7778b99b78-5xtb9             0/1     Pending                      0          45m

test             datalab-auth-deployment-649b6d9-tk6vw           0/1     ContainerCreating            0          45m

test             docs-deployment-79d8fc5878-dtkrd                1/1     Running                      0          45m

test             datalab-api-deployment-6f47c77749-7qwfn         0/1     CreateContainerConfigError   0          45m

test             infrastructure-api-deployment-d97f4f467-hmf4k   1/3     CreateContainerConfigError   0          45m

test             datalab-app-deployment-86b6bf649c-pwrv8         1/1     Running                      0          45m

default          solr-6c6dd54f46-jqkpf                           0/1     ImagePullBackOff             0          45m`
When I look at some of the errors I see the following:

`  Normal   Pulling    44m (x4 over 46m)    kubelet            Pulling image "registry.gitlab.ceh.ac.uk/eip/catalogue/solr:2.81.2"
  Warning  Failed     44m (x4 over 46m)    kubelet            Error: ErrImagePull
  Warning  Failed     44m (x4 over 46m)    kubelet            Failed to pull image "registry.gitlab.ceh.ac.uk/eip/catalogue/solr:2.81.2": rpc error: code = NotFound desc = failed to pull and unpack image "registry.gitlab.ceh.ac.uk/eip/catalogue/solr:2.81.2": failed to resolve reference "registry.gitlab.ceh.ac.uk/eip/catalogue/solr:2.81.2": registry.gitlab.ceh.ac.uk/eip/catalogue/solr:2.81.2: not found
  Warning  Failed     10m (x153 over 46m)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    57s (x197 over 46m)  kubelet            Back-off pulling image "registry.gitlab.ceh.ac.uk/eip/catalogue/solr:2.81.2"
`

When I try to access registry.gitlab.ceh.ac.uk/eip/catalogue/solr:2.81.2 directly I get connection refused.

Same also with registry.gitlab.ceh.ac.uk

Is this a private registry that I need to ask for access to?

**Comment by iwalmsley** [comment]
Hi Geoff,

This catalogue functionality is something that we're currently working on but is incomplete and as you say is stored in a private repository, eventually this will work by default though. In this case you can disable the catalogue service by setting `enabled: false`  in the `values.yaml` file for the `metadata-catalogue` section. Will make a note to document this in the README.

In terms of the other errors I can see, I think it's fair to say that unfortunately it's not yet as easy as running the Helm chart to get you set up, which is definitely the end goal. There are some other steps which you can do yourself but aren't very well documented yet here (such as setting up an OIDC app to manage authentication, and configuring your domain & SSL which are configured values in `values.yaml`), that we're in the process of documenting (@o2a). Will hopefully will have a better README.md up soon which will link you to.

**Comment by geoff-marine** [comment]
Great, thank you for the reply
